# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: quizziz

# The type of the application to build.
type: 'php:8.0'

# Indicate that we want to use composer2, (leave out if you want composer1)
dependencies:
  php:
    composer/composer: '^2'

# The configuration of app when it is exposed to the web.
web:
  commands:
    start: php -S https://main-bvxea6i-i2ocg6masmbgw.fr-4.platformsh.site/ -t public
  locations:
    "/":
      # The public directory of the app, relative to its root.
      root: "web"
      # The front-controller script to send non-static requests to.
      passthru: "/index.php"
